version: '3.1'
services:

  ewm-main-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
    - "6542:5432"
    environment:
    - POSTGRES_DB=ewm-main
    - POSTGRES_USER=ewm-main
    - POSTGRES_PASSWORD=ewm-main
