DROP TABLE IF EXISTS document CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS declaration CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS resource CASCADE;
drop table if exists base_resource cascade;

CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS document
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_date DATE   NOT NULL,
    series     BIGINT NOT NULL,
    number     BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT document_users_fk FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS resource
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    district VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS declaration
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on  DATE    NOT NULL,
    type        VARCHAR NOT NULL,
    document_id BIGINT  NOT NULL,
    state       VARCHAR NOT NULL,
    CONSTRAINT declaration_document_fk FOREIGN KEY (document_id) REFERENCES document
);

CREATE TABLE IF NOT EXISTS requests
(
    declaration_id BIGINT,
    resource_id    BIGINT,
    count          BIGINT,
    status         VARCHAR,
    CONSTRAINT requests_resource_fk FOREIGN KEY (resource_id) REFERENCES resource,
    CONSTRAINT requests_declaration_fk FOREIGN KEY (declaration_id) REFERENCES declaration,
    PRIMARY KEY (declaration_id, resource_id)
);


CREATE TABLE IF NOT EXISTS base_resource
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource_id BIGINT                                  NOT NULL,
    quota       BIGINT                                  NOT NULL,
    start_date  DATE                                    NOT NULL,
    end_date    DATE                                    NOT NULL
);
